AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  ProfileApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.eliascanalesnieto.controller.LambdaHandler::handleRequest
      Runtime: java21
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - arm64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          SECRET_KEY: S3CR3T
          LOG_LEVEL: TRACE
          REGION_NAME: us-west-1
          DB_URL: http://192.168.0.44:8000
          ACCESS_KEY_ID: X
          SECRET_ACCESS_KEY: X
      Events:
        FoodTracker:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY